language: cpp

compiler: gcc

matrix:
  include:
    - name: CUDA 10
      env:
        - CUDA=10.2.89-1
        - CUDA_SHORT=10.2
        - UBUNTU_VERSION=ubuntu1804
      dist: bionic

env:
  - DEBIAN_FRONTEND=noninteractive

before_install:
  - INSTALLER=cuda-repo-${UBUNTU_VERSION}_${CUDA}_amd64.deb
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/${INSTALLER}
  - wget https://developer.download.nvidia.com/compute/cuda/repos/${UBUNTU_VERSION}/x86_64/7fa2af80.pub
  - sudo dpkg -i ${INSTALLER}
  - sudo apt-key add 7fa2af80.pub
  - sudo apt update -qq
  - sudo apt install -y --no-install-recommends
      libopenmpi-dev openmpi-bin openmpi-common
      python3 python3-dev python3-pip make
      cuda-core-${CUDA_SHORT/./-}
      cuda-cudart-dev-${CUDA_SHORT/./-}
      cuda-cufft-dev-${CUDA_SHORT/./-} 
  - CUDA_HOME=/usr/local/cuda-${CUDA_SHORT}
  - LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
  - PATH=${CUDA_HOME}/bin:${PATH}
  - pip3 install cython pytest
  - sudo apt clean

before_script:
  - make clean
  - make production -j
  - make testing -j

script:
  - pytest

sudo: enabled
